# Generated by Django 4.2.9 on 2024-03-27 20:03

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts' , '0001_initial') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='payment' ,
            name='payment_date' ,
            field=models.DateField(auto_now_add=True , null=True) ,
        ) ,
    ]
