# Generated by Django 4.2.9 on 2024-03-27 20:04

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Accounts' , '0002_alter_payment_payment_date') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='payment' ,
            name='payment_date' ,
            field=models.DateField(blank=True , null=True) ,
        ) ,
    ]
