# Generated by Django 4.2.9 on 2024-03-27 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
        ('Accounts' , '0005_payment_payment_received_by') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='payment' ,
            name='payment_received_by' ,
            field=models.ForeignKey(blank=True , default='' , on_delete=django.db.models.deletion.CASCADE ,
                                    to=settings.AUTH_USER_MODEL) ,
        ) ,
    ]
