# Generated by Django 4.2.9 on 2024-03-27 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
        ('DetailEnquiry' , '0006_remove_detail_enquiry_amount_pending') ,
        ('Accounts' , '0007_remove_payment_payment_received_by') ,
    ]

    operations = [
        migrations.AddField(
            model_name='payment' ,
            name='Memo_For' ,
            field=models.ForeignKey(blank=True , default=1 , on_delete=django.db.models.deletion.CASCADE ,
                                    to='DetailEnquiry.detail_enquiry') ,
            preserve_default=False ,
        ) ,
        migrations.AddField(
            model_name='payment' ,
            name='payment_received_by' ,
            field=models.ForeignKey(blank=True , default='' , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to=settings.AUTH_USER_MODEL) ,
        ) ,
    ]
