# Generated by Django 4.2.9 on 2024-03-27 06:04

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Assessment' , '0001_initial') ,
        ('Master' , '0001_initial') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Application' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('sop' , models.FileField(blank=True , null=True , upload_to='sop')) ,
                ('cv' , models.FileField(blank=True , null=True , upload_to='cv')) ,
                ('passport' , models.FileField(blank=True , null=True , upload_to='passport')) ,
                ('ielts' , models.FileField(blank=True , null=True , upload_to='ielts')) ,
                ('gre' , models.FileField(blank=True , null=True , upload_to='gre')) ,
                ('toefl' , models.FileField(blank=True , null=True , upload_to='toefl')) ,
                ('gmat' , models.FileField(blank=True , null=True , upload_to='gmat')) ,
                ('pte' , models.FileField(blank=True , null=True , upload_to='pte')) ,
                ('work_experience' , models.FileField(blank=True , null=True , upload_to='work_experience')) ,
                ('diploma_marksheet' , models.FileField(blank=True , null=True , upload_to='diploma_marksheet')) ,
                ('bachelor_marksheet' , models.FileField(blank=True , null=True , upload_to='bachelor_marksheet')) ,
                ('master_marksheet' , models.FileField(blank=True , null=True , upload_to='master_marksheet')) ,
                ('other_documents' , models.FileField(blank=True , null=True , upload_to='other_documents')) ,
                ('application' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Assessment.assessment')) ,
                ('application_status' , models.ForeignKey(blank=True , max_length=100 , null=True ,
                                                          on_delete=django.db.models.deletion.CASCADE ,
                                                          to='Master.application_status')) ,
            ] ,
        ) ,
    ]
