# Generated by Django 5.0.7 on 2024-08-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
        ('Master', '0026_rename_website_url_course_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status', verbose_name='application status names'),
        ),
    ]
