# Generated by Django 4.2.9 on 2024-03-27 06:04

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
    ]

    operations = [
        migrations.CreateModel(
            name='application_status' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('App_status' , models.CharField(max_length=20)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='assessment_status' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('status' , models.CharField(max_length=20)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='bachelor_requirement' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('requirement' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='country' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('country' , django_countries.fields.CountryField(max_length=2)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='course_levels' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('levels' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='course_requirements' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('requirement' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='current_education' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('current_education' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='documents_required' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('docu_name' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Duolingo_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Overall' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Edu_Level' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('level' , models.CharField(max_length=100)) ,
                ('Stream' , models.CharField(max_length=100)) ,
                ('Percentage' , models.FloatField()) ,
                ('Year_of_Passing' , models.IntegerField()) ,
                ('Name_of_Institute' , models.CharField(max_length=100)) ,
                ('Medium_of_Education' , models.CharField(max_length=100)) ,
                ('Board' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='enquiry_status' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('status' , models.CharField(max_length=20)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Gmat_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Verbal' , models.FloatField()) ,
                ('Quantitative' , models.FloatField()) ,
                ('Analytical' , models.FloatField()) ,
                ('overall' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Gre_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Verbal' , models.FloatField()) ,
                ('Quantitative' , models.FloatField()) ,
                ('Analytical' , models.FloatField()) ,
                ('overall' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='ielts_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Listening' , models.FloatField(null=True)) ,
                ('Reading' , models.FloatField(null=True)) ,
                ('Writing' , models.FloatField(null=True)) ,
                ('Speaking' , models.FloatField(null=True)) ,
                ('Overall' , models.FloatField(null=True)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='intake' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('intake_Name' , models.CharField(max_length=100)) ,
                ('intake_month' , models.CharField(max_length=10)) ,
                ('intake_year' , models.CharField(max_length=10)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='masters_requirement' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('requirement' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='PTE_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Listening' , models.FloatField()) ,
                ('Reading' , models.FloatField()) ,
                ('Writing' , models.FloatField()) ,
                ('Speaking' , models.FloatField()) ,
                ('Overall' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Rejection_Reason' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Refusal_Reason' , models.TextField()) ,
                ('Refusal_Country' , django_countries.fields.CountryField(max_length=2)) ,
                ('Refusal_Visa_Category' , models.CharField(max_length=100)) ,
                ('Refusal_Date' , models.DateField()) ,
                ('Refusal_Letter' , models.FileField(blank=True , upload_to='refusal_letter/')) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='tenth_std_percentage_requirement' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('percentage' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Toefl_Exam' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Listening' , models.FloatField()) ,
                ('Reading' , models.FloatField()) ,
                ('Writing' , models.FloatField()) ,
                ('Speaking' , models.FloatField()) ,
                ('Overall' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='twelfth_std_percentage_requirement' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('percentage' , models.FloatField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Work_Experience' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Company_Name' , models.CharField(max_length=100)) ,
                ('Designation' , models.CharField(max_length=100)) ,
                ('Start_Date' , models.DateField()) ,
                ('End_Date' , models.DateField()) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='university' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('univ_name' , models.CharField(max_length=100)) ,
                ('country' , django_countries.fields.CountryField(blank=True , max_length=2 , null=True)) ,
                ('univ_desc' , models.CharField(blank=True , max_length=1000 , null=True)) ,
                ('univ_logo' , models.ImageField(blank=True , null=True , upload_to='media')) ,
                ('univ_phone' , models.CharField(blank=True , max_length=10 , null=True)) ,
                ('univ_email' , models.EmailField(blank=True , max_length=254 , null=True)) ,
                ('univ_website' , models.URLField(blank=True , null=True)) ,
                ('Remark' , models.TextField(blank=True , null=True , verbose_name='Notes')) ,
                ('Active' , models.BooleanField()) ,
                ('newsletter' ,
                 models.FileField(blank=True , null=True , upload_to='newsletter/' , verbose_name='Newsletters')) ,
                ('application_form' , models.FileField(blank=True , null=True , upload_to='application_forms/' ,
                                                       verbose_name='Application Form')) ,
                ('Duolingo_Exam' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.duolingo_exam')) ,
                ('Gmat_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                 to='Master.gmat_exam')) ,
                ('Gre_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.gre_exam')) ,
                ('PTE_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.pte_exam')) ,
                ('Toefl_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.toefl_exam')) ,
                ('assigned_users' ,
                 models.ForeignKey(blank=True , default='' , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to=settings.AUTH_USER_MODEL)) ,
                ('bachelor_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.bachelor_requirement')) ,
                ('ielts_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.ielts_exam')) ,
                ('masters_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.masters_requirement')) ,
                ('tenth_std_percentage_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.tenth_std_percentage_requirement')) ,
                ('twelfth_std_percentage_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.twelfth_std_percentage_requirement')) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Course' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('course_name' , models.CharField(max_length=100)) ,
                ('Remark' , models.TextField(blank=True , null=True , verbose_name='Notes')) ,
                ('Active' , models.BooleanField()) ,
                ('Duolingo_Exam' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.duolingo_exam')) ,
                ('Gmat_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                 to='Master.gmat_exam')) ,
                ('Gre_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.gre_exam')) ,
                ('PTE_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.pte_exam')) ,
                ('Toefl_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.toefl_exam')) ,
                ('bachelor_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.bachelor_requirement')) ,
                ('course_levels' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.course_levels')) ,
                ('documents_required' ,
                 models.ManyToManyField(blank=True , null=True , to='Master.documents_required')) ,
                ('ielts_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.ielts_exam')) ,
                ('intake' , models.ManyToManyField(blank=True , null=True , to='Master.intake')) ,
                ('masters_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.masters_requirement')) ,
                ('tenth_std_percentage_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.tenth_std_percentage_requirement')) ,
                ('twelfth_std_percentage_requirement' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.twelfth_std_percentage_requirement')) ,
                ('university' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Master.university')) ,
            ] ,
        ) ,
    ]
