# Generated by Django 4.2.9 on 2024-03-27 09:35

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0001_initial') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Services' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Services' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
    ]
