# Generated by Django 4.2.9 on 2024-03-27 10:19

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0002_available_services') ,
    ]

    operations = [
        migrations.AddField(
            model_name='available_services' ,
            name='Price' ,
            field=models.FloatField(blank=True , null=True) ,
        ) ,
    ]
