# Generated by Django 4.2.9 on 2024-03-27 10:30

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0003_available_services_price') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='available_services' ,
            name='Price' ,
            field=models.FloatField(blank=True , help_text='Price in INR' , null=True) ,
        ) ,
    ]
