# Generated by Django 4.2.9 on 2024-03-27 11:16

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0005_alter_edu_level_board_and_more') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Enquiry_Status' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Status' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
    ]
