# Generated by Django 4.2.9 on 2024-03-27 11:33

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0006_detail_enquiry_status') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_Source' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Source' , models.CharField(max_length=100)) ,
                ('Reference_Number' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
    ]
