# Generated by Django 4.2.9 on 2024-03-27 19:39

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0007_enquiry_source') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Mode' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Mode' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Payment_Status' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Status' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Payment_Type' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Type' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
    ]
