# Generated by Django 4.2.9 on 2024-06-26 06:21

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0008_payment_mode_payment_status_payment_type') ,
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('status_name' , models.CharField(max_length=100 , unique=True , verbose_name='Status Name')) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='SubStatus' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('sub_status_name' , models.CharField(max_length=100 , verbose_name='Sub Status Name')) ,
                ('financial_documents_status' , models.CharField(
                    choices=[('Started' , 'Started') , ('Pending' , 'Pending') , ('Waiting' , 'Waiting')] ,
                    max_length=20 , verbose_name='Financial Documents Status')) ,
                ('remarks' , models.TextField(blank=True , null=True , verbose_name='Remarks')) ,
                ('reply_to_remarks' , models.TextField(blank=True , null=True , verbose_name='Reply to Remarks')) ,
                ('admission_status' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , related_name='substatuses' ,
                                   to='Master.admissionstatus')) ,
            ] ,
            options={
                'verbose_name': 'Sub Status' ,
                'verbose_name_plural': 'Sub Statuses' ,
            } ,
        ) ,
    ]
