# Generated by Django 4.2.9 on 2024-06-26 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0009_admissionstatus_substatus') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='substatus' ,
            name='reply_to_remarks' ,
        ) ,
    ]
