# Generated by Django 4.2.9 on 2024-06-26 07:14

import django.db.models.deletion
import tagging.fields
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0012_alter_country_options_remove_country_country_and_more') ,
    ]

    operations = [
        migrations.CreateModel(
            name='campus' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('campus_name' , models.CharField(max_length=100)) ,
                ('campus_location' , models.CharField(max_length=100)) ,
                ('campus_address' , models.CharField(max_length=100)) ,
                ('campus_phone' , models.CharField(max_length=10)) ,
                ('campus_email' , models.EmailField(max_length=254)) ,
                ('campus_website' , models.URLField()) ,
            ] ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Application_deadline' ,
            field=models.DateField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Application_fee' ,
            field=models.FloatField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Application_fee_currency' ,
            field=models.CharField(blank=True , max_length=10 , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Backlogs_allowed' ,
            field=models.IntegerField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Yearly_Tuition_fee' ,
            field=models.FloatField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='country' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.country') ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='other_exam' ,
            field=models.CharField(blank=True , max_length=100 , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='specialisation_tag' ,
            field=tagging.fields.TagField(blank=True , max_length=255 , null=True) ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='website_url' ,
            field=models.URLField(blank=True , null=True) ,
        ) ,
        migrations.AlterField(
            model_name='course' ,
            name='course_name' ,
            field=models.CharField(blank=True , max_length=100 , null=True) ,
        ) ,
        migrations.AlterField(
            model_name='course' ,
            name='university' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.university') ,
        ) ,
        migrations.AddField(
            model_name='course' ,
            name='Campus' ,
            field=models.ManyToManyField(blank=True , null=True , to='Master.campus') ,
        ) ,
    ]
