# Generated by Django 4.2.9 on 2024-06-26 09:00

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0013_campus_course_application_deadline_and_more') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='university' ,
            name='application_form' ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Admission_Requirements' ,
            field=models.TextField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Application_fee' ,
            field=models.FloatField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Application_form_link' ,
            field=models.URLField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Backlogs_allowed' ,
            field=models.IntegerField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Univ_Campus' ,
            field=models.ManyToManyField(blank=True , null=True , to='Master.campus') ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='deadline' ,
            field=models.DateField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='levels' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.course_levels') ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='moi_accepted' ,
            field=models.BooleanField(default=1) ,
            preserve_default=False ,
        ) ,
        migrations.AlterField(
            model_name='university' ,
            name='country' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.country') ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='Application_form' ,
            field=models.FileField(blank=True , null=True , upload_to='application_forms/') ,
        ) ,
    ]
