# Generated by Django 4.2.9 on 2024-06-26 09:04

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0014_remove_university_application_form_and_more') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='university' ,
            name='levels' ,
        ) ,
        migrations.AddField(
            model_name='university' ,
            name='levels' ,
            field=models.ManyToManyField(blank=True , null=True , to='Master.course_levels') ,
        ) ,
    ]
