# Generated by Django 4.2.9 on 2024-07-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0015_remove_university_levels_university_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Campus',
            new_name='Univ_Campus',
        ),
        migrations.RemoveField(
            model_name='university',
            name='Univ_Campus',
        ),
    ]
