# Generated by Django 4.2.9 on 2024-07-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0016_rename_campus_course_univ_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='campus_university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
            preserve_default=False,
        ),
    ]
