# Generated by Django 5.0.7 on 2024-07-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0019_rename_levels_course_levels_level_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='levels',
            new_name='level',
        ),
    ]
