# Generated by Django 5.0.7 on 2024-08-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0021_country_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='diploma_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.diploma_requirement'),
        ),
    ]
