# Generated by Django 5.0.7 on 2024-08-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0022_diploma_requirement_university_diploma_requirement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diploma_requirement',
            new_name='DiplomaRequirement',
        ),
    ]
