# Generated by Django 5.0.7 on 2024-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0024_country_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Application_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
