# Generated by Django 5.0.7 on 2024-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0026_rename_website_url_course_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_fee_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
