# Generated by Django 4.2.9 on 2024-03-27 06:13

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Enquiry' , '0004_alter_enquiry_country_interested') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry' ,
            name='country_interested' ,
            field=django_countries.fields.CountryField(default='GB' , max_length=2) ,
        ) ,
    ]
