# Generated by Django 4.2.9 on 2024-03-27 09:40

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0002_available_services') ,
        ('Enquiry' , '0006_enquiry_interested_services') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry' ,
            name='Interested_Services' ,
            field=models.ManyToManyField(blank=True , default='Counselling' , related_name='Interested_Services' ,
                                         to='Master.available_services') ,
        ) ,
    ]
