# Generated by Django 4.2.9 on 2024-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Enquiry' , '0007_alter_enquiry_interested_services') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry' ,
            name='Interested_Services' ,
        ) ,
    ]
