# Generated by Django 4.2.9 on 2024-03-27 11:33

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0007_enquiry_source') ,
        ('Enquiry' , '0009_enquiry_interested_services') ,
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry' ,
            name='Source_Enquiry' ,
            field=models.ForeignKey(default=1 , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.enquiry_source') ,
            preserve_default=False ,
        ) ,
    ]
