# Generated by Django 4.2.9 on 2024-03-27 11:36

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0007_enquiry_source') ,
        ('Enquiry' , '0010_enquiry_source_enquiry') ,
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry' ,
            name='Source_Enquiry' ,
            field=models.ForeignKey(blank=True , default='Website' , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.enquiry_source') ,
        ) ,
    ]
