# Generated by Django 4.2.9 on 2024-06-26 10:36

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Followup' , '0003_rename_followup_followups') ,
        ('Enquiry' , '0012_remove_enquiry_country_interested_and_more') ,
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry' ,
            name='followup_create' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Followup.followups') ,
        ) ,
    ]
