# Generated by Django 4.2.9 on 2024-07-01 07:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0015_remove_university_levels_university_levels'),
        ('Enquiry', '0013_enquiry_followup_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='level_applying_for', chained_model_field='course_levels', on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='level_applying_for',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='university_interested', chained_model_field='university', on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
    ]
