# Generated by Django 4.2.9 on 2024-07-02 08:26

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0015_remove_university_levels_university_levels'),
        ('Enquiry', '0014_alter_enquiry_course_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country_interested', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
