# Generated by Django 5.0.7 on 2024-07-31 09:25

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0017_alter_enquiry_country_interested'),
        ('Master', '0020_rename_levels_university_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='level_applying_for', chained_model_field='course_levels', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course', verbose_name='Interested Course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='intake_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.intake'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='level_applying_for',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university_interested', chained_model_field='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels', verbose_name='Applying for Level'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_interested', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.university', verbose_name='Interested University'),
        ),
    ]
