# Generated by Django 4.2.9 on 2024-03-27 06:04

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Enquiry' , '0001_initial') ,
        ('Master' , '0001_initial') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Enquiry' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('Father_Occupation' , models.CharField(blank=True , max_length=100 , null=True)) ,
                ('Father_Annual_Income' , models.FloatField(blank=True , null=True)) ,
                ('Twelveth_Document' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Tenth_Document' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Graduation_Marksheet' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Graduation_Certificate' , models.FileField(blank=True , upload_to='documents/')) ,
                ('UG_Marksheet' , models.FileField(blank=True , upload_to='documents/')) ,
                ('UG_Certificate' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Work_Experience_Document' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Passport_Document' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Offer_Letter' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Ielts_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Toefl_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('PTE_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Duolingo_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Gre_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Gmat_Result' , models.FileField(blank=True , upload_to='documents/')) ,
                ('Current_Enquiry' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Enquiry.enquiry')) ,
                ('Duolingo_Exam' ,
                 models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                   to='Master.duolingo_exam')) ,
                ('Gmat_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                 to='Master.gmat_exam')) ,
                ('Gre_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.gre_exam')) ,
                ('PTE_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                to='Master.pte_exam')) ,
                ('Refusal' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                               to='Master.rejection_reason')) ,
                ('Toefl_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.toefl_exam')) ,
                ('Work_Experience' , models.ForeignKey(blank=True , max_length=100 , null=True ,
                                                       on_delete=django.db.models.deletion.CASCADE ,
                                                       to='Master.work_experience')) ,
                ('ielts_Exam' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                  to='Master.ielts_exam')) ,
                ('level' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                             to='Master.course_levels')) ,
            ] ,
        ) ,
    ]
