# Generated by Django 4.2.9 on 2024-03-27 10:30

from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0004_alter_available_services_price') ,
        ('DetailEnquiry' , '0002_remove_detail_enquiry_level_and_more') ,
    ]

    operations = [
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Amount_Pending' ,
            field=models.FloatField(blank=True , null=True) ,
        ) ,
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Confirmed_Services' ,
            field=models.ManyToManyField(blank=True , to='Master.available_services') ,
        ) ,
    ]
