# Generated by Django 4.2.9 on 2024-03-27 11:11

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0004_alter_available_services_price') ,
        ('DetailEnquiry' , '0003_detail_enquiry_amount_pending_and_more') ,
    ]

    operations = [
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Graduation_Education_Details' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    related_name='Graduation_Education_Details' , to='Master.edu_level') ,
        ) ,
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Tenth_Education_Details' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    related_name='Tenth_Education_Details' , to='Master.edu_level') ,
        ) ,
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Twelveth_Education_Details' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    related_name='Twelveth_Education_Details' , to='Master.edu_level') ,
        ) ,
    ]
