# Generated by Django 4.2.9 on 2024-03-27 11:16

import django.db.models.deletion
from django.db import migrations , models


class Migration(migrations.Migration):
    dependencies = [
        ('Master' , '0006_detail_enquiry_status') ,
        ('DetailEnquiry' , '0004_detail_enquiry_graduation_education_details_and_more') ,
    ]

    operations = [
        migrations.AddField(
            model_name='detail_enquiry' ,
            name='Enquiry_Status' ,
            field=models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                    to='Master.detail_enquiry_status') ,
        ) ,
    ]
