# Generated by Django 4.2.9 on 2024-03-27 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('DetailEnquiry' , '0005_detail_enquiry_enquiry_status') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_enquiry' ,
            name='Amount_Pending' ,
        ) ,
    ]
