# Generated by Django 4.2.9 on 2024-06-26 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
        ('Enquiry' , '0012_remove_enquiry_country_interested_and_more') ,
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupStatus' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('status_name' , models.CharField(max_length=100)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Task' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('task_name' , models.CharField(max_length=100)) ,
                ('task_description' , models.TextField()) ,
                ('due_date' , models.DateField()) ,
                ('completed' , models.BooleanField(default=False)) ,
                ('assigned_to' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to=settings.AUTH_USER_MODEL)) ,
            ] ,
        ) ,
        migrations.CreateModel(
            name='Followup' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('followup_date' , models.DateField(auto_now_add=True)) ,
                ('notes' , models.TextField()) ,
                ('next_followup_date' , models.DateField(blank=True , null=True)) ,
                ('assigned_to' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to=settings.AUTH_USER_MODEL)) ,
                ('enquiry' , models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , related_name='followups' ,
                                               to='Enquiry.enquiry')) ,
                ('followup_status' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Followup.followupstatus')) ,
                ('tasks' , models.ManyToManyField(blank=True , related_name='followups' , to='Followup.task')) ,
            ] ,
        ) ,
    ]
