# Generated by Django 4.2.9 on 2024-06-26 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Followup' , '0001_initial') ,
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup' ,
            name='enquiry' ,
        ) ,
    ]
