# Generated by Django 4.2.9 on 2024-06-26 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
        ('Followup' , '0002_remove_followup_enquiry') ,
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followup' ,
            new_name='Followups' ,
        ) ,
    ]
