# Generated by Django 4.2.9 on 2024-06-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL) ,
        ('Master' , '0015_remove_university_levels_university_levels') ,
        ('Followup' , '0003_rename_followup_followups') ,
    ]

    operations = [
        migrations.CreateModel(
            name='Lead' ,
            fields=[
                ('id' ,
                 models.BigAutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=100)) ,
                ('phone_no' , models.CharField(max_length=15)) ,
                ('email_id' , models.EmailField(max_length=254)) ,
                ('remark' , models.TextField(blank=True , null=True)) ,
                ('timestamp' , models.DateTimeField(auto_now_add=True)) ,
                ('assigned_to' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to=settings.AUTH_USER_MODEL ,
                                   verbose_name='For Counsellor')) ,
                ('country' , models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Master.country')) ,
                ('follow_up' , models.ForeignKey(blank=True , null=True , on_delete=django.db.models.deletion.CASCADE ,
                                                 to='Followup.followups' , verbose_name='Follow-up')) ,
                ('purpose' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Master.available_services' ,
                                   verbose_name='Purpose')) ,
                ('source_of_enquiry' ,
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Master.enquiry_source' ,
                                   verbose_name='Source of Enquiry')) ,
            ] ,
        ) ,
    ]
